services:
  portfolio:
    image: ghcr.io/viniciuscestarii/portfolio:${GIT_COMMIT_HASH}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`test.viniciuscestari.dev`)"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3000"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
    networks:
      - public
    deploy:
      update_config:
        order: start-first

networks:
  public:
    external:
      name: public
